#!/usr/bin/env bash
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library - delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" - opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later - it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" - clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." - a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." - a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL - open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

# pause "msg" - wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" - y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY - current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" - like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE - upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name - gh not ready; set it later"
}

# set_var NAME VALUE - set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name - gh not ready; set it later"
}

# finish - clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES - author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# Workers secrets live in .dev.vars for local dev, not .env.
ENV_FILE=".dev.vars"

WRANGLER="npx --yes wrangler@latest"

banner "tally - Cloudflare provisioning"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this wizard needs."
_missing=()
for _c in node npx openssl; do
  command -v "$_c" >/dev/null 2>&1 || _missing+=("$_c")
done
if (( ${#_missing[@]} )); then
  warn "missing: ${_missing[*]}"
  say "Install them, then re-run this script."
  exit 1
fi
step "node $(node --version), npx, openssl - present"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "gh authenticated - CI secrets will be set automatically"
else
  warn "gh not authenticated - the CI token stage will print manual instructions"
fi
note "wrangler runs via npx; no global install needed"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Log in to Cloudflare"
say "A browser window will open for Cloudflare's OAuth flow."
say "You already have an account, so just approve the Wrangler authorisation."
pause
$WRANGLER login
say ""
step "Reading your account id back from Cloudflare."
_whoami=$($WRANGLER whoami 2>/dev/null || true)
_acct=$(printf '%s' "$_whoami" | grep -oE '\b[0-9a-f]{32}\b' | head -1 || true)
if [[ -n "$_acct" ]]; then
  step "Detected account id: $_acct"
  CLOUDFLARE_ACCOUNT_ID="$_acct"
else
  warn "Could not parse the account id automatically."
  say "It's shown in the dashboard URL: dash.cloudflare.com/<account-id>"
  open_url "https://dash.cloudflare.com/"
  ask CLOUDFLARE_ACCOUNT_ID "Paste your account id:"
fi
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Your workers.dev subdomain"
say "Cloudflare gives your account one free subdomain: <word>.workers.dev"
say "Every Worker you deploy lives at <worker-name>.<word>.workers.dev"
say ""
warn "This becomes half of your permanent WebAuthn RP ID. Choose deliberately."
say ""
step "Opening Workers & Pages. Look for your subdomain on the right-hand side."
step "If you have never used Workers, you'll be asked to choose one now."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
say ""
note "Enter just the word - not the full host, no .workers.dev suffix."
ask WORKERS_SUBDOMAIN "Your workers.dev subdomain:"
WORKERS_SUBDOMAIN="${WORKERS_SUBDOMAIN%%.workers.dev}"
write_env WORKERS_SUBDOMAIN "$WORKERS_SUBDOMAIN"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Freeze the Worker name and RP ID"
warn "This is the one irreversible step in this wizard."
say ""
say "The Worker's name plus your subdomain become the WebAuthn RP ID."
say "Passkeys are bound to that exact host. If it ever changes, every"
say "passkey on the instance dies with no migration path, and everyone"
say "re-enrols from scratch. See docs/adr/0002-rp-id-is-permanent.md"
say ""
ask WORKER_NAME "Worker name [tally]:"
WORKER_NAME="${WORKER_NAME:-tally}"
RP_ID="${WORKER_NAME}.${WORKERS_SUBDOMAIN}.workers.dev"
say ""
step "RP ID will be frozen as: $RP_ID"
say ""
if ! confirm "Freeze this permanently?"; then
  say ""
  warn "Aborted. Nothing was frozen - re-run to choose a different name."
  exit 1
fi
write_env WORKER_NAME "$WORKER_NAME"
write_env RP_ID "$RP_ID"

mkdir -p src/shared
cat > src/shared/rp-id.ts <<TS
// FROZEN. See docs/adr/0002-rp-id-is-permanent.md
//
// Never derive this from location.hostname. Changing it destroys every
// passkey on the instance with no migration path.
export const RP_ID = "$RP_ID";
export const ORIGIN = "https://$RP_ID";
TS
printf '  %s✓ wrote%s src/shared/rp-id.ts\n' "$GREEN" "$RESET"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the D1 database"
say "SQLite at the edge. This is where every expense and balance lives."
D1_NAME="$WORKER_NAME"
say ""
step "Creating D1 database: $D1_NAME"
_d1out=$($WRANGLER d1 create "$D1_NAME" 2>&1 || true)
printf '%s\n' "$_d1out" | sed 's/^/  /'
D1_DATABASE_ID=$(printf '%s' "$_d1out" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)
if [[ -z "$D1_DATABASE_ID" ]]; then
  say ""
  warn "Could not parse the database id (it may already exist)."
  note "Run: npx wrangler d1 list"
  ask D1_DATABASE_ID "Paste the database id:"
fi
write_env D1_NAME "$D1_NAME"
write_env D1_DATABASE_ID "$D1_DATABASE_ID"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Create the R2 bucket"
say "Nightly database backups land here."
R2_BUCKET="${WORKER_NAME}-backups"
step "Creating R2 bucket: $R2_BUCKET"
note "If R2 has never been used on this account, Cloudflare may ask you to"
note "enable it in the dashboard first - it is free at this scale."
$WRANGLER r2 bucket create "$R2_BUCKET" 2>&1 | sed 's/^/  /' || {
  warn "Bucket creation failed - enable R2, then re-run this script."
  SKIPPED+=("R2 bucket $R2_BUCKET")
}
write_env R2_BUCKET "$R2_BUCKET"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Update wrangler.jsonc"
say "Paste these bindings into wrangler.jsonc, replacing the empty arrays."
say ""
cat <<JSON
  "name": "$WORKER_NAME",
  "d1_databases": [
    { "binding": "DB", "database_name": "$D1_NAME", "database_id": "$D1_DATABASE_ID" }
  ],
  "r2_buckets": [
    { "binding": "BACKUPS", "bucket_name": "$R2_BUCKET" }
  ]
JSON
say ""
note "Durable Object bindings come later, with the scheduled-work ticket."
note "Every value above is also saved in $ENV_FILE."
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Generate VAPID keys for Web Push"
say "These sign push notifications. Generated locally; nothing leaves this machine."
_vapid=$(npx --yes web-push generate-vapid-keys --json 2>/dev/null || true)
VAPID_PUBLIC_KEY=$(printf '%s' "$_vapid" | grep -oE '"publicKey":"[^"]+"' | cut -d'"' -f4 || true)
VAPID_PRIVATE_KEY=$(printf '%s' "$_vapid" | grep -oE '"privateKey":"[^"]+"' | cut -d'"' -f4 || true)
if [[ -z "$VAPID_PUBLIC_KEY" || -z "$VAPID_PRIVATE_KEY" ]]; then
  warn "Automatic generation failed."
  say "Run this yourself, then paste the two values:"
  note "  npx web-push generate-vapid-keys"
  ask VAPID_PUBLIC_KEY "Public key:"
  ask_secret VAPID_PRIVATE_KEY "Private key:"
else
  step "Generated a VAPID keypair"
fi
write_env VAPID_PUBLIC_KEY "$VAPID_PUBLIC_KEY"
write_env VAPID_PRIVATE_KEY "$VAPID_PRIVATE_KEY"

step "Generating the owner bootstrap secret"
BOOTSTRAP_SECRET=$(openssl rand -base64 32)
write_env BOOTSTRAP_SECRET "$BOOTSTRAP_SECRET"
note "You'll enter this once, in the browser, to claim the instance."
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Deploy the stub Worker"
say "Secrets can only attach to a Worker that exists, so we deploy the stub"
say "first. This also proves your RP ID host is real and reachable."
say ""
note "Make sure wrangler.jsonc is saved with the bindings from stage 7."
pause
$WRANGLER deploy 2>&1 | sed 's/^/  /' || {
  warn "Deploy failed. Fix wrangler.jsonc, then re-run from this stage."
  SKIPPED+=("wrangler deploy")
}
say ""
step "If that succeeded, https://$RP_ID is live."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Push production secrets"
say "Sending the two secrets to the deployed Worker."
for _s in VAPID_PRIVATE_KEY BOOTSTRAP_SECRET; do
  if printf '%s' "${!_s}" | $WRANGLER secret put "$_s" >/dev/null 2>&1; then
    printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$_s"
  else
    warn "could not set $_s"
    SKIPPED+=("Worker secret $_s (npx wrangler secret put $_s)")
  fi
done
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "CI deploy token"
say "A scoped API token lets GitHub Actions deploy without your login."
step "Use the 'Edit Cloudflare Workers' template."
step "Scope it to your account. Copy the token - it is shown only once."
open_url "https://dash.cloudflare.com/profile/api-tokens"
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token (Enter to skip):"
if [[ -n "$CLOUDFLARE_API_TOKEN" ]]; then
  set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  set_var CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
else
  SKIPPED+=("CI token (gh secret set CLOUDFLARE_API_TOKEN)")
fi

finish

printf '  %sFrozen forever:%s %s\n' "$BOLD" "$RESET" "$RP_ID"
printf '  %sRecorded in:%s   src/shared/rp-id.ts, .dev.vars\n\n' "$DIM" "$RESET"
printf '  Next: declare dependencies, then ticket 1 (project foundation).\n\n'
